name: Process and Summarize NSE Data

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    # Runs at the start of every hour. You can adjust the cron schedule as needed.
    # See https://crontab.guru/ for help.
    - cron: "0 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    env: # Define secrets for all steps in the job
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Match your development version

      - name: 3. Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 5. Run data fetcher
        run: python main.py

  summarize:
    runs-on: ubuntu-latest
    needs: fetch # This job will only run if the 'fetch' job completes successfully
    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3. Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4. Install dependencies
        run: pip install -r requirements.txt

      - name: 5. Run AI summarizer
        run: python summarize_articles.py