name: Fetch NSE Data

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  schedule:
    # Runs at the start of every hour. You can adjust the cron schedule as needed.
    # See https://crontab.guru/ for help.
    - cron: '0 * * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Match your development version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetcher
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: python main.py